name: Model Inference Run
description: This template is for requesting a model inference run
title: 'Model Inference: <model_name> <date>'
labels: [model-inference-run]
body:
- type: markdown
  attributes:
    value: Select your model and enter the molecule(s) you want to test. The model
      will be run on the Ersilia Model Hub and the results will be shared with you.
- type: dropdown
  id: model
  attributes:
    label: Model
    multiple: false
    description: Select the target model
    options:
    - Inhibition of N.gonorrhoeae - eos5cl7
    - 3D pharmacophore descriptor - eos4x30
    - ADMET properties prediction - eos7d58
    - ADMETlab models for evaluation of drug candidates - eos2re5
    - ADMETlab-2 - eos2v11
    - Anti-schistosomiasis activity - eos2l0q
    - Antimalarial activity (ABS and sexual stages) - eos80ch
    - Aqueous solubility prediction - eos6oli
    - 'BayeshERG: hERG channel blockade - eos4tcc'
    - Bayesian prediction of synthetic accessibility - eos7pw8
    - Blood-brain barrier penetration - eos1amr
    - Broad spectrum antibiotic activity - eos4e40
    - Broad spectrum antibiotic potential - eos4e41
    - CYP2C9 metabolism - eos5jz9
    - CYP2D6 metabolism - eos7nno
    - CYP450 metabolism - eos44zp
    - ChemGPT-4.7 - eos3cf4
    - Chemical Checker Signaturizer 3D - eos8aox
    - Chemical Checker signaturizer - eos4u6p
    - Classification of hERG blockers and nonblockers - eos30gr
    - Coloring molecules for hERG blockade - eos43at
    - Coloring molecules for interaction with CYP3A4 - eos96ia
    - Coloring molecules for plasma protein binding prediction - eos6ao8
    - Converter of SMILES in Canonical, Selfie, Inchi, Inchi Key form - eos7qga
    - DeepSMILES, an alternate SMILES representation for deep learning - eos2mrz
    - Drug-likeness prediction with Bayesian neural networks - eos9sa2
    - 'DrugTax: Drug taxonomy - eos24ci'
    - ESKAPE pathogen inhibition - eos5xng
    - Electronic spectra and excited state energy - eos3xip
    - ErG 2D Descriptors - eos5guo
    - GDBChEMBL similarity search - eos4b8j
    - GDBMedChem similarity search - eos7jlv
    - HepG2 Toxicity - MMV - eos3le9
    - Human Liver Microsomal Stability - eos31ve
    - Human Plasma Protein Binding (PPB) of Compounds - eos22io
    - Human oral bioavailability prediction - eos2lqb
    - Identifying HDAC3 inhibitors - eos1n4b
    - ImageMol HIV growth inhibition - eos6hy3
    - Inhibition of Eumycetoma from MycetOS - eos4f95
    - Inhibition of Hepatits B virus - eos8lok
    - 'InterDILI: drug-induced injury prediction - eos21q7'
    - Ligand-based prediction of hERG blockade - eos2ta5
    - 'MAIP distillation: antimalarial potential prediction - eos2gth'
    - 'MAIP: antimalarial activity prediction - eos4zfy'
    - Membrane permeability in Mycobacterium tuberculosis - eos8d8a
    - Membrane permeability of fluorescent probes - eos65rt
    - 'MetaTrans: human drug metabolites - eos935d'
    - MolBERT chemical language transformer - eos2thm
    - 'MolBloom: molecule purchasability in ZINC20 - eos8a5g'
    - Molecular Prediction Model Fine-Tuning (MolPMoFiT) - eos9zw0
    - Molecular fingerprint maps based on broadly learned knowledge-based representations
      - eos59rr
    - Molecular representation learning - eos4avb
    - Molecular weight - eos3b5e
    - Morgan Fingerprints - eos4wt0
    - Morgan counts fingerprints - eos5axz
    - Natural product likeness score - eos9yui
    - Neural network-based logP prediction for druglike small molecules - eos9ym3
    - Octanol/water distribution coefficient - eos85a3
    - Organic reaction outcome prediction - eos5qfo
    - PADEL small molecule descriptors - eos7asg
    - Parallel Artificial Membrane Permeability Assay (PAMPA) 7 - eos9tyg
    - Parallel Artificial Membrane Permeability Assay 5 - eos81ew
    - Passive permeability based on simulations - eos2hbd
    - Path-based fingerprint - eos7jio
    - Pharmacophore-guided molecular generation - eos69e6
    - Physicochemical descriptors available from RDKIT - eos8a4x
    - Prediction of hERG Channel Blockers with Directed Message Passing Neural Networks
      - eos30f3
    - Predicts activity of compounds accross the Tox21 panel - eos5smc
    - PubChem Molecular Sampler - eos2hzy
    - REINVENT 4 Mol2MolScaffold - eos57bx
    - RXNFP - chemical reaction fingerprints - eos6aun
    - Retrosynthetic accessibility score - eos2r5a
    - S2DV HepG2 toxicity - eos2fy6
    - SARS-CoV inhibition - eos9f6t
    - 'SARS-CoV-2 antiviral prediction: REDIAL-2020 - eos8fth'
    - SELF-referencIng Embedded Strings - eos6pbf
    - SMILES transformer descriptor - eos2lm8
    - 'STOUT: SMILES to IUPAC name translator - eos4se9'
    - Scaffold Morphing - eos8bhe
    - Scaffold decoration - eos2401
    - Similarity search in ChEMBL, DrugBank and UNPD - eos9c7k
    - Small World Enamine REAL search - eos9ueu
    - Small molecule price prediction - eos7a45
    - ToxCast toxicity panel - eos481p
    - Toxicity and synthetic accessibility prediction - eos92sw
    - Toxicity prediction across the Tox21 panel with semi-supervised learning - eos69p9
    - USR descriptors with pharmacophoric constraints - eos1ut3
    - WHALES scaled - eos24ur
- type: textarea
  id: molecules
  attributes:
    label: Molecules
    description: Enter the molecule(s) you want to test. Use SMILES format. Separate
      multiple molecules with a new line.
